// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsxbK8w6c_pBPxPCYxlCkGgf2a2C6jONQ',
    appId: '1:628312261906:web:0fa5e745ab9fe2960d5fcb',
    messagingSenderId: '628312261906',
    projectId: 'edubridge-58da7',
    authDomain: 'edubridge-58da7.firebaseapp.com',
    storageBucket: 'edubridge-58da7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHenre-CsVu1C2-9jz7s715Oqp_XzIcaQ',
    appId: '1:628312261906:android:034ebfefc89680810d5fcb',
    messagingSenderId: '628312261906',
    projectId: 'edubridge-58da7',
    storageBucket: 'edubridge-58da7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZysAcEzPj_Dv0lVxjvsyD_ZqPdjfNvxo',
    appId: '1:628312261906:ios:4875d901c69d8de20d5fcb',
    messagingSenderId: '628312261906',
    projectId: 'edubridge-58da7',
    storageBucket: 'edubridge-58da7.firebasestorage.app',
    iosBundleId: 'com.example.edubridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZysAcEzPj_Dv0lVxjvsyD_ZqPdjfNvxo',
    appId: '1:628312261906:ios:4875d901c69d8de20d5fcb',
    messagingSenderId: '628312261906',
    projectId: 'edubridge-58da7',
    storageBucket: 'edubridge-58da7.firebasestorage.app',
    iosBundleId: 'com.example.edubridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsxbK8w6c_pBPxPCYxlCkGgf2a2C6jONQ',
    appId: '1:628312261906:web:fa98476afaf509b80d5fcb',
    messagingSenderId: '628312261906',
    projectId: 'edubridge-58da7',
    authDomain: 'edubridge-58da7.firebaseapp.com',
    storageBucket: 'edubridge-58da7.firebasestorage.app',
  );
}
